<?php

const ADMIN_RID = 3;

/**
 * hook_module_implements_alter
 * change hook execution order
 */
function ext_user_module_implements_alter(&$implementations, $hook)
{
  // Name of the hook.
  if (in_array($hook, ['form_alter', 'translated_menu_link_alter'])) {
    // ext_user - last
    $module = 'ext_user';
    if (isset($implementations[$module])) {
      $group = $implementations[$module];
      unset($implementations[$module]);
      $implementations[$module] = $group;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_user_form_user_pass_alter(&$form, &$form_state)
{
  if (!user_has_role(ADMIN_RID)) {
    $form['#prefix'] = '<div class="user-auth-form-wrapper">' .
      '<h1>' . t('Password recovery') . '</h1>';
    $form['#suffix'] = '</div>';
    $form['name']['#title'] = t('E-Mail');
    $form["mail"]["#markup"] = t('The recovery link will be sent to E-Mail above.');
    $form["actions"]["submit"]['#value'] = t('Send me link');
    $form["actions"]["submit"]['#attributes']['class'] = ['btn', 'btn-brand', 'btn-large', 'btn-full-wide'];

    array_unshift($form['#submit'], 'ext_user_user_pass_submit');
  }
}

function ext_user_user_pass_submit($form, $form_state)
{
  // запишем фразу с переводом
  if (variable_get('user_password_reset_text')) {
    variable_set('user_password_reset_text', t(variable_get('user_password_reset_text')));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ext_user_form_user_login_alter(&$form, &$form_state)
{
  $form['#prefix'] =  '<div class="user-auth-form-wrapper">';
  $form['#prefix'] .= '<h1>' . t('Log in') . '</h1>';
  $form['#suffix'] = '</div>';

  $form['name']['#title'] = t('E-Mail');
  $form['name']['#element_validate'][] = 'ext_user_login_name_validate';
  $form["pass"]["#title"] = t('Password');
  unset($form['name']['#description']);
  $form['pass']['#description'] = '<a href="/user/password">' . t('Password recovery') . '</a>';
  $form["actions"]["submit"]['#value'] = t('Log in');
  $form["actions"]["submit"]['#attributes']['class'] = ['btn', 'btn-brand', 'btn-large', 'btn-full-wide'];
}

/**
 * Form element validation handler for the user login form.
 * Allows users to authenticate by username OR email.
 */
function ext_user_login_name_validate($form, &$form_state)
{
  $user = ext_user_user_load_by_login($form_state['values']['name']);
  if ($user->uid) {
    $form_state['values']['name'] = $user->name;
    return TRUE;
  }

  return FALSE;
}

/**
 * Загрузить пользователя по указанному логину
 */
function ext_user_user_load_by_login($login)
{
  // Try loading by email.
  if ($user = user_load_by_mail($login)) {
    return $user;
  }

  // Try loading by username.
  if ($user = user_load_by_name($login)) {
    return $user;
  }
  return user_load(0);
}

function ext_user_process_page(&$vars)
{
  if (arg(0) == 'user') {
    $vars['title'] = '';
    if (isset($vars["tabs"])) {
      unset($vars["tabs"]);
    }
  }
}
