<?php

/**
 * Implements hook_preprocess_page().
 */
function ext_node_preprocess_page(&$vars)
{
  if (arg(0) == 'node' && isset($vars['node'])) {
    if (in_array($vars['node']->type, ['news'])) {
      // статистика

      $vars['title'] = '';
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function ext_node_preprocess_node(&$vars)
{
  $node = $vars['node'];

  // -- Изображения
  $images = [];
  if ($vars['view_mode'] == 'teaser' && isset($node->field_image_teaser)) {
    $images[] = $vars['content']['field_image_teaser'][0];
  }
  elseif (isset($node->field_images)) {
    foreach ($vars['content']['field_images']['#items'] as $key => $file) {
      $images[] = $vars['content']['field_images'][$key];
    }
  }
  elseif (isset($node->field_image)) {
    $images[] = $vars['content']['field_image'][0];
  }
  $vars['images'] = $images;

  // -- Информация
  if (in_array($node->type, ['news'])) {
    $vars['date'] = date('d.m.Y', $node->created);
    $vars['stats'] = statistics_get($node->nid);
  }

  // -- Полная ссылка для шар
  $vars['node_url_full'] = url('node/' . $node->nid, ['absolute' => true]);
}

/**
 * Implements hook_node_presave()
 */
function ext_node_node_presave($node)
{
  if (in_array($node->type, ['news'])) {
    // обработка текста перед сохранением
    require_once(drupal_get_path('module', 'ext_node') . '/includes/preprocessors.ext_node.inc');
    ext_node_prepare_content_to_save($node);
  }
}

/**
 * Implements hook_form_FORMID_alter().
 */
function ext_node_form_node_form_alter(&$form, &$form_state)
{
  if ($GLOBALS['theme'] != 'seven') {
    // для всех Материалов
    // убрать закладку Ревизии и поменять местами остальные закладки
    if (isset($form["revision_information"]["#access"])) {
      $form["revision_information"]["#access"] = false;
      $form["options"]["#weight"] = $form["author"]["#weight"] - 1;
    }

    // для Новостей
    if (in_array($form["type"]["#value"], ['news'])) {
      // убрать неиспользуемые опции
      $form["options"]["promote"]["#access"] = false;
      $form["options"]["sticky"]["#access"] = false;

      // изменить формат поля Body на редактор по умолчанию
      if (isset($form["body"])) {
        $lang = $form["body"]["#language"];
        if ($form["body"][$lang][0]["#type"] == 'text_format' && !$form["body"][$lang][0]["#format"]) {
          $form["body"][$lang][0]["#format"] = 'filtered_html';
        }
      }

      // предварительная обработка текстов
      require_once (drupal_get_path('module', 'ext_node') . '/includes/preprocessors.ext_node.inc');
      ext_node_prepare_content_to_edit($form);
    }
  }
}


/**
 * Implements hook_form_alter().
 */
function ext_node_form_alter(&$form, &$form_state, $form_id)
{

}
